[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "bazaszachowa-tools"
version = "1.0.0"
requires-python = ">=3.12"
authors = [
  {name = "Andrzej Kulesza", email = "andykrk22@gmail.com"},
]
description = "Tools for maintenance database for bazaszachowa"

dependencies = [
    "beautifulsoup4==4.15.0",
    "certifi==2026.7.22",
    "charset-normalizer==3.5.1",
    "chess==1.11.2",
    "dnspython==2.8.0",
    "idna==3.19",
    "mysql-connector-python==26.7.0",
    "pymongo==4.17.0",
    "python-dateutil==2.9.0.post0",
    "requests==2.34.2",
    "six==1.17.0",
    "soupsieve==2.9.2",
    "typing_extensions==4.16.0",
    "Unidecode==1.4.0",
    "urllib3==2.7.0",
    "zstandard==0.25.0",
]
[project.optional-dependencies]
dev = [
    "ast_serialize==0.8.0",
    "librt==0.15.0",
    "mypy==2.3.1",
    "mypy_extensions==1.1.0",
    "pathspec==1.1.1",
    "ruff==0.16.3"
]
curl_cffi = [
    "cffi==2.1.1",
    "curl_cffi==0.16.0"
]

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = [
    ".idea",
    ".venv",
    "__pycache__",
    "repeatable_tasks/downloaded_zips",
    "repeatable_tasks/pgns",
    "chess_scrappers",
]

[tool.setuptools]
py-modules = []


[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # Pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
    "SIM",  # flake8-simplify\
    "RET",  # flake8-return
]
ignore = [
    "E501",  # line-too-long (handled by formatter)
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]
python_version = "3.12"
strict = true

check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_any_generics = true

no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

ignore_missing_imports = true

exclude = [
    "^python/chess_scrappers/",
]

