name: C++ workflow on FreeBSD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-freebsd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Build
        uses: vmactions/freebsd-vm@v1
        with:
          release: '14.4'
          run: |
            pkg update
            pkg install -y cmake gcc mysql80-client
            cmake -S cpp -B cpp/build
            cmake --build cpp/build --parallel 2
